### ISSUE TITLE
Metaspades terminated with an error exit status (21)

### ISSUE THREAD

**Issue by ycuesta** [nf-core/mag#719]
### Description of the bug

Dear community. 
We are running the mag pipeline and facing problems with the metaspades step. 
The error looks like:
ERROR nextflow.processor.TaskProcessor - Error executing process > NFCORE_MAG:MAG:METASPADES
Caused by:
Process NFCORE_MAG:MAG:METASPADES terminated with an error exit status (21)

Thanks for the support!!! any idea about this issue with metaspades?
Yesid

### Command used and terminal output

```console

```

**Comment by ycuesta** [comment]
This is the print screen of the error:
![Image](https://github.com/user-attachments/assets/c72a30ae-640b-4743-adac-3c9fe43c2d21)
In our case, MEGAHIT is running well, and we have the contigs from the assembly step. Are both programs (Spades and MegaHit) comparable in terms of accuracy? This is in case we cannot run spades and stay only with the MEGAHIT results.
Many thanks.
Yesid

**Comment by jfy133** [comment]
Hi @ycuesta 👋

You've only posted the top half of the error message so it's hard to say unfortunately.

It would be best if you could upload your `.nextflow.log` file which should have the whole error message. 

Otherwise, both assemblers work pretty well. 

Generally people say that megahit you get slightly higher quality contigs but are shorter, whereas metaspades gives you longer contigs but high risk of errors/misassemblies. So it depends what you need the contigs for, and what downstream steps to be performing - but this depends per researcher/project

**Comment by ycuesta** [comment]
Many thanks James.
Sorry. I will provide the .log files. On the other hand, we are pretending to retrieve MAGs from our shotgun data.
Many thanks.
Yesid

**Comment by jfy133** [comment]
Hello, as I didn't hear back, I'll assume this was solved somehow. Feel free to re-open if still unresolved.

**Comment by ycuesta** [comment]
Hello James. 
I am attaching the nextflow.log file. We have decided to split spades however the pipeline still is not working.
Many thanks and I appreciate any support.

[nextflow.log](https://github.com/user-attachments/files/18856393/nextflow.log)

**Comment by ycuesta** [comment]
Sorry, I meant skip spades ;)

**Comment by ycuesta** [comment]
Dear James.
Here a new .log file from today. The error persists, this time with megahit.
I really appreciate any feedback.
Yesid


[nextflow.log](https://github.com/user-attachments/files/18869622/nextflow.log)

**Comment by jfy133** [comment]
Hi @ycuesta !

Your error from lines 1976 in your config file:

```
Feb-19 13:42:38.917 [TaskFinalizer-1] ERROR nextflow.processor.TaskProcessor - Error executing process > 'NFCORE_MAG:MAG:MEGAHIT (AB1239)'

Caused by:
  Process exceeded running time limit (16h)


```

Please see https://nf-co.re/docs/usage/getting_started/configuration#tuning-workflow-resources
