### ISSUE TITLE
Switch to DSL 2

### ISSUE THREAD

**Issue by skrakau** [nf-core/mag#74]

**Comment by skrakau** [comment]
- [ ] Compare results to latest DSL1 version
- [ ] Clean up usage of `meta` vs. other fields
- [ ] Make process names more consistent
- [ ] Update `nf-core/test-datasets`
- [ ] Generalize modules where possible and port to nf-core/modules
- [ ] Check params printed to summary, inconsistently at the moment (printed if value from `nextflow_schema.json` does not match default given in `nextflow.config`, default type in schema does need to match type)

**Comment by skrakau** [comment]
The current CAT BioContainer does not work with the latest CAT database, because of different Diamond versions (see https://github.com/nf-core/mag/issues/90). However, just creating a new BioContainer with the according Diamond version does not solve such issues for the future: see https://github.com/dutilh/CAT/issues/54

Need to think about alternatives, if there will be no solution.

**Comment by skrakau** [comment]
Use of `nf-amazon` plugin for full-size test: see https://github.com/nextflow-io/nextflow/issues/1964

**Comment by skrakau** [comment]
CAT BioContainer is updated and works now for current CAT database (tbb.bio.uu.nl/bastiaan/CAT_prepare/CAT_prepare_20210107.tar.gz). Log term maintenance will be handled separately.

**Comment by skrakau** [comment]
Solved in #162 , #171

**Comment by gailrosen** [comment]
[pipeline_report.txt](https://github.com/nf-core/mag/files/6444837/pipeline_report.txt)
[software_versions.csv](https://github.com/nf-core/mag/files/6444838/software_versions.csv)

I don't know why, but I still get this error.   [2021-05-07 14:21:46.114194] 47 bin(s) found!  

Command error:
  Error: Database was built with a different version of Diamond and is incompatib
le.
  [2021-05-07 14:34:47.300571] ERROR: DIAMOND finished abnormally.

Work dir:
  /ifs/groups/eces450650Grp/data/Assembly_Binning_old/work/81/95fee99d939f76a9ae3
1784c62007d

Tip: you can replicate the issue by changing to the process work dir and entering
 the command `bash .command.run`



The workflow was completed at 2021-05-07T14:47:11.875034-
04:00 (duration: 1h 4m 7
s)

The command used to launch the workflow was as follows:

  nextflow run nf-core/mag -resume -profile singularity --input 'CSJP002A_{R1,R2}
.fastq.gz' -c nextflow.config --max_memory 186.GB --max_cpus 20 --kraken2_db k2_p
luspf_20210127.tar.gz --cat_db CAT_prepare_20210107.tar.gz --outdir results_cat
